In [8]:
#Importing libraries
#!pip install tensorflow
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#Load the data

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [10]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

# Data Transformation

In [11]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [12]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [13]:
df.drop(columns = ['Exited'])

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [14]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'])
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1                 1   
1                  1        112542.58       0                 0   
2                  0        113931.57       1                 1   
3                  0         93826.63       0                 1   
4                  1         79084.10       0                 0   
...              ...              ...     ...               ...   
9995               0         96270.64       0                 1   
9996               1        101699.77       0                 1   
9997               1         42085.58       1                 1   
9998               0         92888.52       1                 0   
9999               0         38190.78       0                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

# Model Building

In [15]:
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1                 1   
1                  1        112542.58       0                 0   
2                  0        113931.57       1                 1   
3                  0         93826.63       0                 1   
4                  1         79084.10       0                 0   
...              ...              ...     ...               ...   
9995               0         96270.64       0                 1   
9996               1        101699.77       0                 1   
9997               1         42085.58       1                 1   
9998               0         92888.52       1                 0   
9999               0         38190.78       0                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

In [16]:
sc = StandardScaler()
x = df.drop(columns=['Exited'])
y = df['Exited']

In [17]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [18]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [19]:
xtrain

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [20]:
#Initialize model
ann = Sequential()

#Add hidden layer
ann.add(Dense(units=10,activation='relu'))   # units is nothing but no.of neurons , Dense is use to add layer


#Add output layer
ann.add(Dense(units=1, activation='sigmoid'))   #
#Establish the connection between the layers
ann.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics='accuracy')  # adadelta is Gradiant descent,loss is error

#Fit the data
ann.fit(xtrain,ytrain, epochs=100)  # epochs is no .of Iteration



Epoch 1/100


250/250 [==============================] - 11s 18ms/step - loss: 0.6795 - accuracy: 0.5444
Epoch 2/100
250/250 [==============================] - 6s 24ms/step - loss: 0.6787 - accuracy: 0.5459
Epoch 3/100
250/250 [==============================] - 5s 20ms/step - loss: 0.6779 - accuracy: 0.5471
Epoch 4/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6770 - accuracy: 0.5494
Epoch 5/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6761 - accuracy: 0.5509
Epoch 6/100
250/250 [==============================] - 2s 8ms/step - loss: 0.6752 - accuracy: 0.5523
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.6743 - accuracy: 0.5534
Epoch 8/100
250/250 [==============================] - 4s 17ms/step - loss: 0.6734 - accuracy: 0.5548
Epoch 9/100
250/250 [==============================] - 3s 12ms/step - loss: 0.6724 - accuracy: 0.5565
Epoch 10/100
250/250 [==============================] - 2s 9ms/step - loss: 0.671

250/250 [==============================] - 4s 15ms/step - loss: 0.6200 - accuracy: 0.6526
Epoch 73/100
250/250 [==============================] - 4s 14ms/step - loss: 0.6193 - accuracy: 0.6543
Epoch 74/100
250/250 [==============================] - 3s 13ms/step - loss: 0.6186 - accuracy: 0.6554
Epoch 75/100
250/250 [==============================] - 4s 15ms/step - loss: 0.6179 - accuracy: 0.6570
Epoch 76/100
250/250 [==============================] - 4s 14ms/step - loss: 0.6172 - accuracy: 0.6576
Epoch 77/100
250/250 [==============================] - 3s 14ms/step - loss: 0.6165 - accuracy: 0.6584
Epoch 78/100
250/250 [==============================] - 4s 15ms/step - loss: 0.6158 - accuracy: 0.6603
Epoch 79/100
250/250 [==============================] - 3s 13ms/step - loss: 0.6151 - accuracy: 0.6615
Epoch 80/100
250/250 [==============================] - 4s 14ms/step - loss: 0.6144 - accuracy: 0.6634
Epoch 81/100
250/250 [==============================] - 3s 14ms/step - loss: 0.6137 - 

In [21]:
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [22]:
ypred = ann.predict(xtest)
ypred

63/63 [==============================] - 2s 18ms/step


array([[0.43035877],
       [0.42249098],
       [0.4743266 ],
       ...,
       [0.24310835],
       [0.43478405],
       [0.2816813 ]], dtype=float32)

In [23]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [24]:
print(classification_report(ytest,ypred))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [18]:
a = 5
b = 10

In [21]:
a == b

False

In [23]:
False == 0
True == 1

True

In [24]:
ypred > 0.5

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [25]:
ypred = ypred > 0.5
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [26]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [27]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.80      0.75      0.78      1585
           1       0.23      0.28      0.26       415

    accuracy                           0.66      2000
   macro avg       0.52      0.52      0.52      2000
weighted avg       0.68      0.66      0.67      2000



# Hyperparameter Tuning

In [26]:
#!pip install -U keras-tuner

  Obtaining dependency information for keras-tuner from https://files.pythonhosted.org/packages/2b/39/21f819fcda657c37519cf817ca1cd03a8a025262aad360876d2a971d38b3/keras_tuner-1.4.6-py3-none-any.whl.metadata
  Obtaining dependency information for kt-legacy from https://files.pythonhosted.org/packages/16/53/aca9f36da2516db008017db85a1f3cafaee0efc5fc7a25d94c909651792f/kt_legacy-1.0.5-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/128.9 kB ? eta -:--:--
   -------------------------------------- - 122.9/128.9 kB ? eta -:--:--
   ---------------------------------------- 128.9/128.9 kB 1.5 MB/s eta 0:00:00


# **Tuning the ANN Model**
- Selecting the best optimizer




In [27]:
import keras_tuner as kt

In [28]:
def optimizer_selection(hp):
    #initialize the model
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop'])
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = 'accuracy')
    return model

In [29]:
tuner = kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',
    max_trials=3
)

In [30]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))

Trial 3 Complete [00h 00m 24s]
val_accuracy: 0.8059999942779541

Best val_accuracy So Far: 0.8144999742507935
Total elapsed time: 00h 01m 07s


In [31]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [32]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 [==============================] - 5s 12ms/step - loss: 0.4226 - accuracy: 0.8217 - val_loss: 0.4136 - val_accuracy: 0.8205
Epoch 2/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4107 - accuracy: 0.8275 - val_loss: 0.4025 - val_accuracy: 0.8285
Epoch 3/100
250/250 [==============================] - 4s 16ms/step - loss: 0.4005 - accuracy: 0.8335 - val_loss: 0.3933 - val_accuracy: 0.8370
Epoch 4/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3914 - accuracy: 0.8369 - val_loss: 0.3850 - val_accuracy: 0.8425
Epoch 5/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3831 - accuracy: 0.8424 - val_loss: 0.3768 - val_accuracy: 0.8460
Epoch 6/100
250/250 [==============================] - 7s 28ms/step - loss: 0.3765 - accuracy: 0.8478 - val_loss: 0.3698 - val_accuracy: 0.8470
Epoch 7/100
250/250 [==============================] - 5s 21ms/step - loss: 0.3708 - accuracy: 0.8504 - val_loss: 0.3644 - val_accuracy: 

250/250 [==============================] - 4s 17ms/step - loss: 0.3380 - accuracy: 0.8608 - val_loss: 0.3373 - val_accuracy: 0.8605
Epoch 58/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3380 - accuracy: 0.8611 - val_loss: 0.3344 - val_accuracy: 0.8630
Epoch 59/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3380 - accuracy: 0.8625 - val_loss: 0.3355 - val_accuracy: 0.8625
Epoch 60/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3380 - accuracy: 0.8618 - val_loss: 0.3359 - val_accuracy: 0.8615
Epoch 61/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3379 - accuracy: 0.8615 - val_loss: 0.3339 - val_accuracy: 0.8650
Epoch 62/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3378 - accuracy: 0.8625 - val_loss: 0.3342 - val_accuracy: 0.8630
Epoch 63/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3377 - accuracy: 0.8630 - val_loss: 0.3358 - val_accuracy: 0.864

In [34]:
model.evaluate(xtrain,ytrain)

250/250 [==============================] - 4s 15ms/step - loss: 0.3335 - accuracy: 0.8634


[0.3334701955318451, 0.8633750081062317]

# Regression

In [35]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Regression.csv')
df

price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [36]:
x = df.iloc[:,1:]
y = df['price']

In [37]:
x = sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [38]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [39]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))
ann.add(Dense(units=20, activation='relu'))

ann.add(Dense(units=1))

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
25/25 [==============================] - 9s 82ms/step - loss: 255952.4531 - val_loss: 262736.8125
Epoch 2/100
25/25 [==============================] - 1s 26ms/step - loss: 255580.9375 - val_loss: 262324.9062
Epoch 3/100
25/25 [==============================] - 1s 23ms/step - loss: 255085.2031 - val_loss: 261717.0156
Epoch 4/100
25/25 [==============================] - 1s 32ms/step - loss: 254302.3750 - val_loss: 260693.4531
Epoch 5/100
25/25 [==============================] - 1s 26ms/step - loss: 253042.5469 - val_loss: 259118.3750
Epoch 6/100
25/25 [==============================] - 1s 24ms/step - loss: 251123.6250 - val_loss: 256711.4062
Epoch 7/100
25/25 [==============================] - 1s 25ms/step - loss: 248238.7031 - val_loss: 253274.6250
Epoch 8/100
25/25 [==============================] - 1s 27ms/step - loss: 244185.2969 - val_loss: 248412.2344
Epoch 9/100
25/25 [==============================] - 1s 23ms/step - loss: 238640.6562 - val_loss: 241838.0156
Epoch 10/1

Epoch 77/100
25/25 [==============================] - 1s 23ms/step - loss: 721.1294 - val_loss: 704.6238
Epoch 78/100
25/25 [==============================] - 1s 53ms/step - loss: 690.1821 - val_loss: 675.4885
Epoch 79/100
25/25 [==============================] - 2s 78ms/step - loss: 658.0867 - val_loss: 647.6680
Epoch 80/100
25/25 [==============================] - 1s 41ms/step - loss: 629.8184 - val_loss: 622.0560
Epoch 81/100
25/25 [==============================] - 1s 25ms/step - loss: 602.8819 - val_loss: 595.6160
Epoch 82/100
25/25 [==============================] - 1s 23ms/step - loss: 576.3700 - val_loss: 571.8159
Epoch 83/100
25/25 [==============================] - 1s 24ms/step - loss: 552.7629 - val_loss: 550.0220
Epoch 84/100
25/25 [==============================] - 1s 29ms/step - loss: 529.3229 - val_loss: 528.0519
Epoch 85/100
25/25 [==============================] - 1s 25ms/step - loss: 507.6614 - val_loss: 509.7035
Epoch 86/100
25/25 [==============================] - 1

In [40]:
yp = ann.predict(xtest)
yp

7/7 [==============================] - 1s 14ms/step


array([[473.13885],
       [520.646  ],
       [497.74506],
       [538.62476],
       [656.6293 ],
       [339.51575],
       [361.48413],
       [374.11853],
       [731.76056],
       [508.7225 ],
       [482.5036 ],
       [504.10504],
       [497.26288],
       [361.5774 ],
       [542.76373],
       [488.07172],
       [573.01154],
       [544.7128 ],
       [484.0946 ],
       [494.47516],
       [474.34644],
       [605.56506],
       [439.91968],
       [574.5967 ],
       [423.02536],
       [518.6948 ],
       [382.94016],
       [498.66318],
       [536.7657 ],
       [349.7729 ],
       [444.357  ],
       [642.78   ],
       [558.27325],
       [537.939  ],
       [600.88934],
       [554.9038 ],
       [409.66113],
       [567.1981 ],
       [567.24695],
       [525.92957],
       [420.98364],
       [740.1775 ],
       [520.9518 ],
       [525.7538 ],
       [521.8931 ],
       [468.856  ],
       [531.28253],
       [522.025  ],
       [580.2261 ],
       [464.75604],


In [41]:
from sklearn.metrics import r2_score

In [42]:
r2_score(ytest,yp)

0.9625969238867474